FORM/urls.py
from django.contrib import admin
from django.urls import path,include
from app1.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',index,name='index'),
    path('app1/',include('app1.urls',namespace='app1')),
    
]

app1/urls.py
from django.urls import path
from app1 import views

app_name = 'app1'

urlpatterns = [ 

    path('students',views.students,name='students'),
    path('sonu',views.sonu,name='sonu'),
]

app1/models.py
from django.db import models


# Create your models here.

class Persons(models.Model):
    name = models.CharField(max_length=20)
    age = models.IntegerField()
    gender = models.CharField(max_length=10)
    phno = models.IntegerField()


    def __str__(self):
        return self.name

app1/forms.py
from django import forms
from app1.models import *

class Personsform(forms.ModelForm):
    class Meta:
        model = Persons
        fields = '__all__'
        

app1/views.py
from django.shortcuts import render
from app1.forms import Personsform
from app1.models import Persons

# Create your views here.

def index(request):
    return render(request,'app1/index.html',{'msg':'This is Index Page'})


def students(request):
    data = ['tabusha','vamsi','srinu','kiran','teja','raju']
    context = {'data':data}
    return render(request,'app1/student.html',context)
    
def sonu(request):
    form = Personsform()
    if request.method == 'POST':
        form = Personsform(request.POST)
        if form.is_valid():
            name=form.cleaned_data['name']
            age=form.cleaned_data['age']
            gender=form.cleaned_data['gender']
            phno=form.cleaned_data['phno']
            A = Persons(name=name,age=age,gender=gender,phno=phno)
            A.save()
            form = Personsform()    
        else:
            print('notvalid')
    context = {'msg':'this is students page','form':form}
    return render(request,'app1/sonu.html',context)

templates/app1/index.html
{% extends 'base.html' %}
{% block b1 %}
    {{msg}}
{% endblock  %}

templates/app1/sonu.html
{% extends 'base.html' %}
{% block b1 %}   
    <form action="" method="post"novalidate>
        {% csrf_token %}
         <div class="form-group row">
            {% for i in form %}
                <label class="col-sm-1 offset-sm-5 col-form-label"  for="">{{i.label_tag}}</label>
                <div class="col-sm-1">{{i}}{{i.errors|striptags}}</div>
            {% endfor %}
         </div>
        <!-- {{form.as_p}} -->
       <div  class="col-sm-2 offset-sm-6"><input class="btn btn-success" type="submit" value="SUBMIT"></div>
    </form>
{% endblock  %}

templates/app1/student.html
{% extends 'base.html' %}
{% block b1 %}
    {% for i in data %}
       <ol>{{i}}</ol> 
    {% endfor %}
{% endblock  %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>BASE</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
</head>
<body>
    <div class="container">
        <div class="sticky-top">
            <h1 class="text-center p-3 mb-2 bg-info text-dark">Django Web Development : SAMPLE</h1>
                
                    <a class="btn btn btn-info" href="{% url 'index' %}">HOME</a> 
                    <a class="btn btn btn-info" href="{% url 'app1:students' %}">STUDENTS</a> 
                    <a class="btn btn btn-info" href="{% url 'app1:sonu' %}">FORM</a>
                
        </div>
        <div class="c1 text-center">
            {% block b1 %}
            {% endblock %}
        </div>
        <div class="container fixed-bottom">
            <h1 class="text-center p-3 mb-2 bg-info text-dark">Thanks for visiting</h1>
        </div>
    </div>
</body>
</html>